version: "3.9"

services: 
    database:
        image: postgres
        container_name: teste
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=queries_challenge
        volumes:
            - pgdata:/data/postgres
        
volumes:
    pgdata: 
        driver: local


# docker-compose up -d
# docker-compose stop
# docker-compose start
# docker-compose up --force-recreate -d